CREATE TABLE IF NOT EXISTS gps_posicoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tablet_satelital VARCHAR(100) NOT NULL UNIQUE,
    latitude DECIMAL(10, 6) NOT NULL,
    longitude DECIMAL(10, 6) NOT NULL,
    capturado_em TIMESTAMP NOT NULL,
    observacao VARCHAR(255)
);
