CREATE TABLE gps_posicoes (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tablet_satelital VARCHAR2(100 CHAR) NOT NULL,
    latitude NUMBER(10, 6) NOT NULL,
    longitude NUMBER(10, 6) NOT NULL,
    capturado_em TIMESTAMP NOT NULL,
    observacao VARCHAR2(255 CHAR),
    CONSTRAINT uk_gps_posicoes_tablet UNIQUE (tablet_satelital)
);
